version: '3.8'

services:
  nginx:
    build:
      context: ./dockers
      dockerfile: Dockerfile.nginx
    container_name: nginx-container-load-balencer
    ports:
      - "8989:80"
    volumes:
      - ./dockers/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server_1
      - server_2

  server_1:
    build:
      context: ./dockers
      dockerfile: Dockerfile.server_1
    container_name: server-container-1
    ports:
      - "1111:9000"
    volumes:
      - .:/app
  server_2:
    build:
      context: ./dockers
      dockerfile: Dockerfile.server_2
    container_name: server-container-2
    ports:
      - "2222:9001"
    volumes:
      - .:/app
